AllCops:
  TargetRubyVersion: 2.6

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'lib/schwarznasenschaf/commands/info.rb'

Metrics/ModuleLength:
  Exclude:
    - 'lib/schwarznasenschaf/commands/info.rb'