AllCops:
  TargetRubyVersion: 2.6

Style/Documentation:
  Enabled: false

Style/ClassAndModuleChildren:
  EnforcedStyle: compact

Metrics/MethodLength:
  Max: 15

Metrics/ModuleLength:
  Exclude:
    - 'lib/schwarznasenschaf/admin/commands/info.rb'

Metrics/LineLength:
  Max: 120